version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Running tests
      - npm run test

artifacts:
  files:
    - '**/*'
  base-directory: 'build' # or the directory where your build outputs are stored

cache:
  paths:
    - 'node_modules/**/*'
